jorenham/optype

optype/_can.py
I'm not sure why pyright didn't like `Self` in this case, though...
=> Fix `CanAIterSelf` not being an `AsyncGenerator` subtype

.pre-commit-config.yaml, optype/_can.py, pyproject.toml
- sync pre-commit ruff version with pyproject.toml
- re-enable `PLW1641` globally
=> Post ruff upgrade tweaks

README.md, optype/__init__.py, optype/_can.py, tests/test_protocols.py
Added
- `CanEnterSelf`
- `CanWithSelf`
and 
- `CanAEnterSelf`
- `CanAsyncWithSelf`
=> add `*Self` aliases for context manager interfaces

optype/_can.py, optype/_does.py, optype/_has.py, tests/helpers.py
This'll make instance checks faster on `python<3.12`, and improves compatibility with Python 3.13.
=> Prefer `typing_extensions` imports for `Protocol` and `runtime_checkable`

.github/workflows/ci.yml, .pre-commit-config.yaml, .vscode/extensions.json, .vscode/settings.json, optype/_does.py, poetry.lock, pyproject.toml
This bumps basedpyright, pre-commit, and ruff to their latest versions.
The Python 3.13 tests are now run on the beta 4 release.
=> Update development dependencies

optype/__init__.py, tests/types/test_slice.py
This ensures that `optype.types` is always available, e.g.
```pycon
>>> import optype as opt
>>> isinstance(slice(42), opt.types.Slice)
True
```
=> Export `optype.types`

.markdownlint.yaml, README.md, optype/__init__.py, optype/_can.py, optype/copy.py, tests/numpy/test_copy.py
> [!IMPORTANT]
> This is a backwards-compatible breaking change! 
This moves the following runtime-protocols from `optype` to `optype.copy`:
- `CanCopy(Self)`
- `CanDeepcopy(Self)`
- `CanReplace(Self)`
> [!NOTE]
> The `optype.copy` is exported in `optype`.
> So `import optype as opt` will allow you to access e.g. `opt.copy.CanCopy`.
=> Extract `copy`-related `Can*` protocols to  the new `optype.copy` namespace

README.md, optype/__init__.py, optype/_can.py, optype/pickle.py, tests/numpy/test_pickle.py
> [!IMPORTANT]
> This is a backwards-incompatible breaking change! 
This moves the following runtime-protocols from `optype` to `optype.pickle`:
- `CanGetnewargs`
- `CanGetnewargsEx`
- `CanGetstate`
- `CanSetstate`
- `CanReduce`
- `CanReduceEx`
> [!NOTE]
> The `optype.pickle` module is exported through `optype`.
> So `import optype as opt` will allow you to access e.g. `opt.rick.CanReduce`.
=> Extract `pickle`-related `Can*` protocols to  the new `optype.pickle` namespace

README.md, optype/__init__.py, optype/_has.py, optype/dataclasses.py
> [!IMPORTANT]
> This is a backwards-incompatible breaking change! 
This moves the following runtime-protocols from `optype` to `optype.dataclasses`:
- `HasDataclassFields`
> [!NOTE]
> The `optype.dataclasses` module is exported through `optype`.
> So `import optype as opt` will allow you to access e.g. `opt.dataclasses.HasDataclassFields`.
=> Move `optype.HasDataclassFields` to  the new `optype.dataclasses` namespace

optype/_can.py, optype/_do.py, optype/_does.py, optype/_has.py, optype/_utils.py, tests/helpers.py, tests/test_protocols.py
This changes the `__module__` to `'optype'` for the `optype.*` re-exports of the following submodules:
- `optype._can.Can*`
- `optype._has.Has*`
- `optype._does.Does*`
- `optype._do.do_*` (except the re-exports from `builtins` and `operator`)
fixes #119
=> Remove the private parts of `__module__` in `optype` exports

README.md, optype/__init__.py, optype/inspect.py, optype/string.py, tests/test_string.py
=> `optype.string`: a better variant of the `string` standard library

README.md, optype/__init__.py, optype/_types_impl.py, optype/_types_impl.pyi, optype/inspect.py, optype/types.py, poetry.lock, pyproject.toml, tests/test_inspect.py, tests/test_pickle.py
This module exists since optype 0.5, but *was* undocumented, untested, and (therefore) buggy.
Several new functions were also added.
=> `optype.inspect` A collection of functions for typing inspection at runtime

.github/workflows/ci.yml, .pre-commit-config.yaml, README.md, examples/functor.py, examples/twice.py, optype/_has.py, optype/inspect.py, optype/numpy/_scalar.py, optype/numpy/_shape.py, pyproject.toml, tests/numpy/test_any_array.py, tests/numpy/test_any_scalar.py, tests/numpy/test_array.py, tests/numpy/test_scalar.py, tests/numpy/test_shape.py, tests/test_can.py, tests/test_copy.py, tests/test_does.py, tests/test_inspect.py, tests/test_pickle.py, tests/test_protocols.py, tests/test_string.py, tests/test_typing.py, tests/test_version.py
This also reworked the `optype.numpy` shape aliases, so that both mypy and pyright treat them the same.
Additionally, the examples were simplified; making them more to-the-point, and mypy-valid.
=> Complete mypy support, with `strict=true`

.github/workflows/ci.yml, .pre-commit-config.yaml, .vscode/settings.json, README.md, optype/numpy/__init__.py, optype/numpy/_any_array.py, optype/numpy/_any_dtype.py, optype/numpy/_array.py, optype/numpy/_dtype.py, optype/numpy/_scalar.py, optype/numpy/_shape.py, optype/numpy/_ufunc.py, optype/numpy/ctypeslib.py, tests/numpy/test_any_array.py, tests/numpy/test_scalar.py
- BREAKING: `Any*Array` aliases no longer accept bare scalars
- BREAKING: no longer allow include `ctypes.Array` in `Any*Array`, as `npt.ArrayLike` also doesn't allow this
- use `TypeAliasType` instead of `TypeAlias` for large unions
- stripped the private submodule name from `__module__` of the `Protocol`s
=> improve readability of `optype.numpy` type aliases and protocols

optype/_core/_can.py, optype/_core/_does.py, optype/_core/_has.py, optype/_core/_utils.py, optype/copy.py, optype/dataclasses.py, optype/dlpack.py, optype/inspect.py, optype/json.py, optype/pickle.py, optype/types/_typeforms.pyi, optype/typing.py, uv.lock
This fixes (at least) the following issue:
```pycon
>>> op.CanSequence[int, float]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/joren/.pyenv/versions/3.12.7/lib/python3.12/typing.py", line 398, in inner
return func(*args, **kwds)
^^^^^^^^^^^^^^^^^^^
File "/home/joren/.pyenv/versions/3.12.7/lib/python3.12/typing.py", line 1110, in _generic_class_getitem
_check_generic(cls, params, len(cls.__parameters__))
File "/home/joren/.pyenv/versions/3.12.7/lib/python3.12/site-packages/typing_extensions.py", line 2947, in _check_generic
raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments"
TypeError: Too few arguments for <class 'optype.CanSequence'>; actual 2, expected at least 2
```
=> workaround a PEP 696 bug in `typing_extensions.Protocol`  affecting `CanSequence`

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, uv.lock
... and re-enabled `basedpyright --verifytypes` now that microsoft/pyright#9446 is fixed
=> bump `basedpyright` to `1.21.1` (`pyright 1.1.389`)

.pre-commit-config.yaml, optype/json.py, optype/typing.py, pyproject.toml, uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.7.4
=> bump `ruff` to `0.7.4`

README.md, optype/typing.py, tests/test_typing.py
```py
import optype.typing as opt
class A: ...
class B(A): ...
def must_have_type_a(a: opt.Just[A]) -> None:
assert type(a) is A
must_have_type_a(A())  # accepted
must_have_type_a(B())  # rejected (mypy + pyright (requires the latests typeshed))
```
```py
import optype.typing as opt
def only_int_pls(x: opt.JustInt, /) -> int:
assert type(x) is int
return x
f(42)  # accepted
f(True)  # rejected (mypy + pyright)
```
note that for some reason, both mypy and pyright allow assigning `Never` to `Just` and `JustInt`
=> experimental `Just` and `JustInt` types in `optype.typing`

optype/numpy/_sequence_nd.py, optype/numpy/_to.py, tests/numpy/test_to.pyi
ref: python/mypy#18184
resolves #194
=> workaround for a mypy bug with recursive sequences types

README.md, optype/numpy/_to.py, tests/numpy/test_to.pyi
unlike the `ToInt*` ones, the `ToJustInt*` types reject scalars/arrays of `builtins.bool` and `np.bool_`
=> `ToJustInt` scalar- and array-likes in `optype.numpy`

optype/typing.py
=> fix `typing_extensions` import on `python>=3.13`

README.md, optype/numpy/_to.py
This adds the following type aliases to `optype.numpy`
- `ToBoolStrict{1,2,3}D`
- `ToIntStrict{1,2,3}D`
- `ToFloatStrict{1,2,3}D`
- `ToComplexStrict{1,2,3}D`
- `ToArrayStrict{1,2,3}D`
These are completely disjoint (i.e. non-overlapping), which makes them suitable for defining shape-type specific overloads on array-like input.
=> `onp.To*Strict{1,2,3}D`: array-like aliases with strict shape-type

README.md, optype/numpy/_array.py
This adds the following type-aliases to `optype.numpy`:
- `Array0D`
- `CanArray0D`
Note that both only accept `np.ndarray` and reject "bare" scalars (i.e. `np.generic` subtype instances).
resolves #200
=> 0-d numpy array aliases

optype/numpy/_to.py, pyproject.toml, tests/numpy/test_to.pyi
These now also accept `CanArray0D` as scalars and combinations of sequences and ndarray's. 
Before this change, static type checkers would reject the following example.
```py
import optype.numpy as onp
three_0d: onp.Array0D[np.int_] = np.array(3, np.int_)
three_1d: onp.ToInt1D =  [3, np.int_(3), three_0d]
```
even though it was valid at runtime:
```pycon
>>> np.array([3, np.int_(3), np.array(3)])
array([3, 3, 3])
```
The tests for these aliases have also been improved.
=> accept more valid numpy array-likes in `optype.numpy.To*{1,2,3,N}`

.pre-commit-config.yaml, optype/_core/_can.py, pyproject.toml, tests/test_typing.py, uv.lock
Pyright now fully supports `optype.typing.Just`
=> bump `basedmypy` to `2.8.0` and `basedpyright` to `1.22.1`

optype/numpy/_any_array.py, optype/numpy/_any_dtype.py, optype/numpy/ctypeslib.py, tests/numpy/test_any_dtype.py
changed in `optype.numpy`:
- add `Any[U]IntDType` and `Any[U]IntArray` for the `np.int_` and `np.uint` scalar types
- assume `np.[u]intc` is 32-bits, and update `Any[U]Int32{DType,Array}` accordingly (but not vice-versa)
- assume `np.[u]longlong` is 64-bits, and update `Any[U]Int64{DType,Array}` accordingly (but not vice-versa). 
The `[U]IntC` and  `[U]LongLong` aliases will be removed in a future release.
=> `numpy.Any[U]Int{DType,Array}` for `np.int_`

optype/numpy/_any_array.py, optype/numpy/_any_dtype.py, optype/numpy/_to.py
=> prefer `Just{Float,Complex}` over `Just[{float,complex}]` in `optype.numpy`

optype/__init__.pyi, pyproject.toml
=> lazy submodule imports

README.md, optype/__init__.pyi, optype/_core/_just.py, tests/core/test_just.py
useful as `bytes` promotion (requires `mypy>=1.15`)
=> add `JustBytes`

README.md, optype/numpy/__init__.py, optype/numpy/_is.py, tests/numpy/test_is.py
Closes #254.
---
To check whether a given object is an instance of `Array{0,1,2,3,N}D`, in a way that static type-checkers also understand it, the following PEP 742 typeguards can be used:
<table>
<tr>
<th>typeguard</th>
<th>narrows to</th>
<th>shape type</th>
</tr>
<tr>
<th colspan="2"><code>optype.numpy._</code></th>
<th><code>builtins._</code></th>
</tr>
<tr>
<td><code>is_array_nd</code></td>
<td><code>ArrayND[ST]</code></td>
<td><code>tuple[int, ...]</code></td>
</tr>
<tr>
<td><code>is_array_0d</code></td>
<td><code>Array0D[ST]</code></td>
<td><code>tuple[()]</code></td>
</tr>
<tr>
<td><code>is_array_1d</code></td>
<td><code>Array1D[ST]</code></td>
<td><code>tuple[int]</code></td>
</tr>
<tr>
<td><code>is_array_2d</code></td>
<td><code>Array2D[ST]</code></td>
<td><code>tuple[int, …
=> `optype.numpy.is_` typeguard

.pre-commit-config.yaml, optype/_core/_can.py, pyproject.toml, uv.lock
- `ruff`: 0.9.2 -> 0.9.3
- `sp-repo-review`: 2024.8.19 -> 2025.1.22
- `basedpyright`: 1.24.0 -> 1.26.0
- `tox`: 4.23.2 -> 4.24.1
=> Update the development dependencies

optype/_core/_just.py, optype/typing.py
This changes the `Just*` types into *purely structural types* by marking them with `@final`. The reported LSP violations by mypy and pyright are false positives, since the LSP is a nominal thing, and therefore does not apply here.
Addtionally, this unifies the metaclasses of the concrete (non-generic) `Just*` protocols, to make things a bit more DRY. This does not change their behavior in any way.
=> mark `optype.Just*` as `@final` and simplify metaclasses

README.md, optype/numpy/__init__.py, optype/numpy/random.py
[SPEC 7](https://scientific-python.org/specs/spec-0007/) -compatible type aliases.
The `optype.numpy.random` module provides three type aliases: `RNG`, `ToRNG`, and
`ToSeed`.
In general, the most useful one is `ToRNG`, which describes what can be
passed to `numpy.random.default_rng`. It is defined as the union of `RNG`, `ToSeed`,
and `numpy.random.BitGenerator`.
The `RNG` is the union type of `numpy.random.Generator` and its legacy dual type,
`numpy.random.RandomState`.
`ToSeed` accepts integer-like scalars, sequences, and arrays, as well as instances of
`numpy.random.SeedSequence`.
=> new `optype.numpy.random` submodule

optype/inspect.py, optype/numpy/_scalar.py, optype/numpy/_to.py, tests/numpy/test_to.pyi
This fixes an issue where the 2- and 3-d `optype.numpy.To(2|3)D` array-like types were not assignable to their `*ND` variants, e.g.:
```py
import numpy as np
import optype.numpy as onp
def fn(x: onp.ToFloatND) -> int:
return np.asarray(x).size
def f2(x: onp.ToFloat2D) -> int:
return fn(x)  # will no longer be rejected
```
This additionally works around a regression in `typing_extensions==4.13.0` that results in a `TypeError` being raised when taking the union of `typing.TypeAliasType` and `typing_extension.TypeAliasType` on (at least) Python 3.12.
=> fix `To{}(2|3)D` not being assignable to `To{}ND`

.github/workflows/ci.yml
mostly because the github code scanning tool was complaining about this
=> read-only ci permissions

optype/numpy/_any_array.py, optype/numpy/_array.py, optype/numpy/_is.py, optype/numpy/_shape.py, optype/numpy/ctypeslib.py, optype/numpy/random.py
this unifies `Any` and `tuple[int, ...]` as shape-types using the "gradual tuple" `tuple[Any, ...]` for numpy `><2.1` and `>=2.1`.
=> numpy version agnostic gradual shape type defaults

optype/numpy/_ufunc.py
`optype.numpy.CanArrayFunction` falsely rejected assigning types whose  `__array_function__` parameters `args` and `kwargs` used any value type besides `object` and `Any`.
=> `numpy.CanArrayFunction` contravariance assignability fix

.github/workflows/ci.yml
ref: https://github.com/data-apis/array-api-typing/pull/18/files#r2134923886
=> use `github.ref` instead of `github.sha` in the `concurrency.group` of `CI`

optype/numpy/_array.py
This removes the PEP 696 default of the first `optype.numpy.CanArrayND` generic type parameter (covariant and bound to `np.generic`). This is technically a breaking change, but given its absence from the docs, I don't expect it to be likely that this will cuase issues for optype users.
This works around a path-dependent bug in Pyright (<=1.1.403) that has recently been causing a lot of issues in scipy-stubs.
See scipy/scipy-stubs#745, scipy/scipy-stubs#742, and scipy/scipy-stubs#741 for more info about this pyright bug.
=> `optype.numpy.CanArrayND`: remove scalar type parameter default

README.md, optype/_core/_can.py
For example, one can now write `CanMul[int]` instead of `CanMul[int, int]`.
=> `Can` binop return type param defaults to input param

README.md, optype/numpy/_to.py
This adds array-like type aliases to `optype.numpy` for the `float16`, `float32`, and `complex64` scalar types.
=> `optype.numpy` array-like types for `float16`, `float32`, and `complex64`

.github/workflows/ci.yml, pyproject.toml, uv.lock
Next week `3.14.0rc1` will released, and the final release is expected for 2025-10-07 (see [PEP 745](https://peps.python.org/pep-0745/)).
=> preliminary support for python 3.14

pyproject.toml
The uv build backend has been stabailized since `uv >= 0.7.19`, and has become the default build backend for  `uv init --pacakge` and `uv init --lib`. Configuration is easier, and I'm guessing that it's also quite a bit faster than hatchling (and all other build backends). 
<sub>I'm starting to become an astral fanboy, but that's *probably* just me being sane.</sub>
Oh yea I also sprinkled some comments around the `pyproject.toml`, which should help look for the (start of) tool sections.
=> `uv` build backend

pyproject.toml
Apparently the uv build backend doesn't add this automatically like hatchling did.
=> explicit `license-files`

optype/numpy/_any_array.py, optype/numpy/_any_dtype.py, optype/numpy/_compat.py, optype/numpy/compat.py, tests/numpy/test_any_array.py
So that's `AnyLongDoubleArray` and `AnyLongDoubleDType` from `optype.numpy` we're talking about here.
Oh yea I also got rid of an unused `_compat` module in `optype.numpy`.
=> make `AnyLongDouble*` compatible with `numpy<2.2`

optype/numpy/_to.py
Apparently stringified annotations in `TypeAliasType` will silently be inferred as `Unknown`....
=> fix `CanArrayStrict{1,2,3}D`

pyproject.toml
most of the keywords were shamelessly stolen from `typing_extensions`
=> improved project metadata

optype/numpy/ctypeslib.py
This avoids an `AttributeError` from being raised (at runtime) on Windows + Python 3.14 when doing e.g. `import optype.numpy.ctypes`.
... or at least, that's what typeshed seems to suggest here:
https://github.com/python/typeshed/blob/ec184feeee93a545028833de6a1d62ffbb766f2c/stdlib/ctypes/__init__.pyi#L288-L296
=> `optype.numpy.ctypes`: no complex C-types on windows

optype/numpy/ctypeslib.py, tests/numpy/test_ctypes.py
These were previously unions of many variants (e.g. 19 for `Integer`), which could have lead to type-checker spaghetti error reports.
closes #445 (but with an alternative approach)
=> `optype.numpy.ctypes`: simplified abstract numberic aliases
