- README.md
- examples/functor.py
- examples/twice.py
- pyproject.toml
This adds `examples/twice.py`, and a new "Example" section to the `README.md`, and resolves #36
> Introductory usage example

- poetry.lock
- pyproject.toml
- tests/test_beartype.py
See [beartype/beartype](https://github.com/beartype/beartype)
> Test using beartype

- .pre-commit-config.yaml
See https://github.com/DetachHead/basedpyright/issues/430
> Use the new basedpyright pre-commit hook

- optype/inspect.py
- tests/helpers.py
- tests/numpy/test_sctypes.py
- tests/test_protocols.py
> Add the `optype.inspect` module

- README.md
- optype/numpy/__init__.py
- optype/numpy/_shape.py
- pyproject.toml
- tests/__init__.py
- tests/helpers.py
- tests/numpy/test_shape.py
- tests/test_beartype.py
> Numpy shape aliases: `AtLeast{N}D` and `AtMost{N}D`

- optype/numpy/_sctype.py
- poetry.lock
- pyproject.toml
this includes [pyright 1.1.372](https://github.com/microsoft/pyright/releases/tag/1.1.372)
> bump `basedpyright` to `1.14.0`

- .vscode/settings.json
- optype/_can.py
- optype/_do.py
- optype/_does.py
- optype/_has.py
- optype/_utils.py
- optype/inspect.py
- optype/numpy/_any_array.py
- optype/numpy/_any_dtype.py
- optype/numpy/_scalar.py
- optype/pickle.py
- poetry.lock
- pyproject.toml
- tests/test_inspect.py
... even though (based)pyright should always be preferred
> Preliminary mypy support

- .github/workflows/ci.yml
- README.md
- optype/numpy/_any_array.py
- optype/numpy/_any_dtype.py
- optype/numpy/_any_scalar.py
- optype/numpy/_array.py
- optype/numpy/_compat.py
- optype/numpy/_ufunc.py
- pyproject.toml
Added:
- `optype.numpy.AnyStringArray`
- `optype.numpy.AnyStringDType`
> Support for `numpy.dtypes.StringDType`

- .vscode/settings.json
- README.md
- optype/dlpack.py
- pyproject.toml
- tests/test_dlpack.py
> `optype.dlpack`: DLPack types and enums

- optype/numpy/_array.py
- tests/numpy/test_array.py
> fix `optype.numpy.CanArray`

- README.md
- optype/numpy/__init__.py
- optype/numpy/_array.py
- optype/numpy/_shape.py
- optype/numpy/_to.py
- tests/numpy/test_to.pyi
> `optype.numpy.To*` coercible scalar- and array-likes

- .pre-commit-config.yaml
- optype/_core/_do.py
- optype/inspect.py
- optype/numpy/ctypeslib.py
- pyproject.toml
- tests/numpy/test_array.py
- tests/numpy/test_ufunc.py
- tests/test_protocols.py
- uv.lock
https://github.com/astral-sh/ruff/releases/tag/0.8.1
> bump `ruff` to `0.8.1`

- examples/functor.py
- examples/twice.py
- optype/numpy/_scalar.py
- tests/test_copy.py
- tests/test_do.py
- tests/test_inspect.py
- tests/test_pickle.py
- tests/test_protocols.py
- tests/test_string.py
- tests/test_types.py
- tests/test_typing.py
- tests/test_version.py
#205 apparently didn't catch all of them 😅 
cc @lucascolley
> fix (more) `typing_extensions` imports on `python>=3.13`

- README.md
> Added missed optype documentation

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- .vscode/extensions.json
- optype/numpy/_any_dtype.py
- pyproject.toml
- tests/numpy/test_to.pyi
- uv.lock
> migrate from `codespell` to `typos`

- README.md
- optype/numpy/_array.py
> new `onp.Matrix` and `onp.MArray[{0,1,2,3}D]` aliases

- README.md
- optype/numpy/_any_dtype.py
- tests/numpy/test_any_dtype.py
see also https://github.com/numpy/numpy/issues/28072
> `onp.AnyBytes8DType` for `np.dtype("c")`

- README.md
- optype/numpy/_to.py
- tests/numpy/test_to.pyi
> new `onp.To[Just]{Float64,Complex128}*` aliases

- .github/workflows/publish-pypi.yml
> PyPI trusted publishing

- optype/numpy/_any_dtype.py
- added `type[JustInt]` to `Any{Int,Long}DType` on `numpy<2`
- added `type[JustInt | JustFloat | JustComplex]` to `AnyNumberDType`
closes #235
> add the missing `Just` types to `onp.Any*DType`

- README.md
- optype/__init__.pyi
- optype/_core/_just.py
- tests/core/test_just.py
> add `JustObject`

- optype/_core/_has.py
- optype/_utils.py
> BREAKING: change `HasFunc` and `HasWrapped` generic type params

- pyproject.toml
using the vscode "even better TOML" plugin
> format `pyproject.toml`

- optype/numpy/_any_dtype.py
- optype/numpy/_dtype.py
- optype/numpy/_dtype_attr.py
- optype/numpy/_is.py
intentionally left undocumented, as the interface might change a bit
> new `optype.numpy.ToDType` aliases

- README.md
- optype/numpy/_to.py
> add literal `onp.To[Just]{False,True}` aliases

- optype/numpy/_any_array.py
- optype/numpy/_array.py
- optype/numpy/_ctypeslib.pyi
- optype/numpy/_dtype.py
- optype/numpy/_is.py
- optype/numpy/_scalar.py
In line with https://github.com/numpy/numpy/pull/28982
According to the "gradual typing guarantee" this should not be a breaking change. But speaking from experience, that's almost never holds up in practice.
> prefer gradual type parameter defaults

- README.md
- optype/numpy/_shape.py
> optionally gradual unbounded shape-types

- pyproject.toml
- uv.lock
https://mypy-lang.blogspot.com/2025/07/mypy-117-released.html
> bump `mypy` to `1.17.0`

- optype/numpy/_to.py
This removes the (redundant) `np.matrix` from the union type in the `optype.numpy.To*Strict2D` and `optype.numpy.To*Strict3D` types.
This also simplifies the (non-strict) `To*` array-like aliases by joining the `CanArray*D` protocols it uses with the scalar types, using `__array__` protocols that have no `__len__`. This helps speed up type-checker analysis time of e.g. in overload-heavy function defitions.
> `optype.numpy.To*` array-like alias simplifications

- pyproject.toml
- uv.lock
This makes `tox` significantly more powerful as a task runner.
See also https://github.com/tox-dev/tox-uv
> `tox-uv` & more tox envs

- examples/.ruff.toml
- optype/_core/_can.py
- optype/_core/_do.py
- optype/inspect.py
- optype/numpy/_any_array.py
- optype/numpy/_shape.py
- optype/numpy/_to.py
- optype/numpy/ctypeslib.py
- optype/types/_typeforms.pyi
- pyproject.toml
- scripts/.ruff.toml
- scripts/my.py
- tests/.ruff.toml
- tests/numpy/test_any_array.py
... although that's a euphemism, given the net diff of -98 in `pyproject.toml`
> ruff config cleanup

- optype/_core/_do.py
- tests/core/test_do.py
> move the type-tests in `_core/_do.py` to `tests/do.py`

- README.md
- optype/_core/_can.py
> `Can*Same[-T?, +R?]` with `-> Self | R`

- tests/core/test_can.py
- tests/core/test_protocols.py
> move the `Can*` tests to a more appropriate place

- .github/copilot-instructions.md
> If you can't beat them; join them.
> instructions for copilot

- optype/numpy/__init__.py
see https://github.com/jorenham/numpy-typing-compat/issues/45
> prepare for the new `numpy-typing-compat` versioning

- README.md
follow-up of https://github.com/facebook/pyrefly/issues/1170
> add pyrefly badge and improve badge style consistency

- README.md
> update `copy.CanReplace` docs

- optype/numpy/_dtype.py
- optype/numpy/_to.py
This works around https://github.com/facebook/pyrefly/issues/1162, unblocking https://github.com/scipy/scipy-stubs/issues/893
> update all `optype.numpy.To*` to use `TypeAliasType`

- optype/numpy/_ctypeslib.pyi
- optype/numpy/ctypeslib.py
- tests/numpy/test_ctypes.py
because apparently there weren't any
> `optype.numpy.ctypes` tests
